name: labels

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v2
      -
        # https://github.com/crazy-max/ghaction-github-labeler
        name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
