name: labels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'
  pull_request:
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      # same as global permissions
      contents: read
      # required to update labels
      issues: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          dry-run: ${{ github.event_name == 'pull_request' }}
